require_relative '../vagrant_commons'

Vagrant.configure '2' do |config|
    config.vm.box = 'sylvainjoyeux/ubuntu-15.10-x86_64'
    config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 4096
    end

    config.vm.provision 'shell', path: '../scripts/ubuntu_country_setup.sh',
        args: ['archive.ubuntu.com', VagrantCommons.ubuntu_archive_url]
end

