require_relative '../vagrant_commons'

Vagrant.configure '2' do |config|
    config.vm.box = 'sylvainjoyeux/ubunty-16.04-x86_64'
    config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 4096
        libvirt.cpu_feature name: 'avx', policy: 'disable'
        libvirt.cpu_feature name: 'avx2', policy: 'disable'
    end
    config.vm.synced_folder '/home/doudou/dev/rock/cache', '/opt/rock_cache',
        type: '9p',
        accessmode: 'mapped',
        owner: 'client'
    config.vm.synced_folder '../../gems/autoproj', '/opt/autoproj',
        type: '9p'

    config.cache.scope = :box
    #config.cache.enable :gem
    config.cache.synced_folder_opts = Hash[
        type: '9p',
        accessmode: 'mapped',
        owner: 'client'
    ]

    config.vm.provision 'shell', path: '../scripts/ubuntu_country_setup.sh',
        args: ['us.archive.ubuntu.com', VagrantCommons.ubuntu_archive_url]
    config.vm.provision 'file',
        source: File.join(Dir.home, '.gitconfig'),
        destination: '.gitconfig'
    config.vm.provision 'file',
        source: 'autoproj_bootstrap/autoprojrc',
        destination: '.autoprojrc'
    config.vm.provision 'file',
        source: '/home/doudou/dev/gems/autoproj/bin/autoproj_bootstrap',
        destination: 'autoproj_bootstrap'
    #config.vm.provision 'shell',
    #    path: 'apt_setup.sh'
    config.vm.provision 'shell',
        path: 'autoproj_bootstrap/bootstrap.sh',
        privileged: false
end

